### ISSUE TITLE
Reorder the y axis in the plot generated by `autoplot()`

### ISSUE THREAD

**Issue by albertotb** [joshuaulrich/microbenchmark#18]
Is there any way to reorder the y axis in the plot generated by `autoplot()`?

Possible implementation, mostly borrowed from `print`:

```{r}
autoplot.microbenchmark <- function(object, order, ...,
                                    log=TRUE,
                                    y_max=1.05 * max(object$time)) {
  if (!requireNamespace("ggplot2"))
    stop("Missing package 'ggplot2'.")
  y_min <- 0
  object$ntime <- convert_to_unit(object$time, "t")
  %% -----------------------------------------------------------------------
  if (!missing(order)) {
      s <- summary(object)
      if (order %in% colnames(s)) {
        object$expr <- factor(object$expr, levels = levels(object$expr)[order(s[[order]])])
      }
      else {
        warning("Cannot order results by", order, ".")
      }
  }
  %% -----------------------------------------------------------------------
  plt <- ggplot2::ggplot(object, ggplot2::aes_string(x="expr", y="ntime"))
  plt <- plt + ggplot2::coord_cartesian(ylim=c(y_min , y_max))
  plt <- plt + ggplot2::stat_ydensity()
  plt <- plt + ggplot2::scale_x_discrete(name="")
  y_label <- sprintf("Time [%s]", attr(object$ntime, "unit"))
  plt <- if (log) {
    plt + ggplot2::scale_y_log10(name=y_label)
  } else {
    plt + ggplot2::scale_y_continuous(name=y_label)
  }
  plt <- plt + ggplot2::coord_flip()
  plt
}
```

**Comment by eddelbuettel** [comment]
Giving a thumbs up -- I am looking at the exact same issue.  Would be nice to make that option available.

**Comment by eddelbuettel** [comment]
As reordering is also helpful in `print()` or the boxplot, I pulled the essential two lines out (for now at least) and made them a helper function in my helper functions script, see [the file now committed](https://github.com/eddelbuettel/dang/blob/master/R/reorderMicrobenchmarkResults.R).

**Comment by eddelbuettel** [comment]
@joshuaulrich It's been a few days/weeks since I played with that. I think I concluded at the time that it _is_ beneficial to reorder the returned object to drive _both_ `print()` and `autoplot()` (and alike) at once.

Of course a day or two after I committed the helper function I reference I found yet another example of mine where already did the same, but simpler...

**Comment by albertotb** [comment]
@joshuaulrich It's been a while, so its probably a version thing. According to [this](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) resource soemthing like this should work, but I have not tested it.

```
plt <- ggplot2::ggplot(object, ggplot2::aes(x=.data[["expr"]], y=.data[["ntime"]]))
```

**Comment by eddelbuettel** [comment]
Function `stats::reorder()` may be helpful too.
