### ISSUE TITLE
microbenchmarking in browser() with {} doesnt work

### ISSUE THREAD

**Issue by trafficonese** [joshuaulrich/microbenchmark#19]
### Description
I am trying to run some microbenchmarks inside a shinyApp by using the `browser()`.

When the code is a 1-liner it works as expected, but when the code is wrapped in curly brackets it doesn't work. 

I am not sure if that is a `microbenchmark()` issue or more a `browser()` issue.

### Minimal, reproducible example
```r
library(shiny)
library(data.table)
library(microbenchmark)

ui <- fluidPage(
  tableOutput("tbl")
)

server <- function(input, output, session) {
  df <- reactive({
    irisDT <- copy(iris)
    setDT(irisDT)
    
    browser()
    
    ## 1-liner works
    mc <- microbenchmark(
      a = iris[iris$Species == "setosa",],
      b = irisDT[Species == "setosa"] 
    ); mc
    
    ## Multi-liner doesn't work
    mc <- microbenchmark(
      a = {
        df <- iris[iris$Species == "setosa",]
        df[df$Sepal.Length > 5,]
      },
      b = {
        dt <- irisDT[Species == "setosa"]
        dt[Sepal.Length > 5,]
      } 
    ); mc
    
    irisDT
  })
  output$tbl <- renderTable({
    df()
  })
}

shinyApp(ui, server)
```

### Error message
`debug at #3: df <- iris[iris$Species == "setosa", ]`

### Session Info

```r
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 
```

**Comment by joshuaulrich** [comment]
Thanks for the report, and the reproducible example. Here's a minimal example that doesn't depend on Shiny.

```r
func <- function() {
  browser()
  microbenchmark(a = { x <- c("hello"); x <- c(x, "world") })
}
func()
```

Do you know if this worked in prior versions of `microbenchmark` and/or R?  My guess is that it did not, and this behavior is a function of how the debugger works.  To illustrate that point, here's an example that demonstrates this isn't specific to `microbenchmark()`.

```r
func <- function() {
  browser()
  a <- {
    print("hello")
    print("world")
    NULL
  }
}
func()
```

**Comment by trafficonese** [comment]
Thanks for the quick reply.

Unfortunately I dont know if it worked in previous versions, but I also guess it didn't.
I also experienced the same behaviour with if-else conditions inside the browser.
