### ISSUE TITLE
Untimed setup expression

### ISSUE THREAD

**Issue by thk686** [joshuaulrich/microbenchmark#2]
Feature request. Add a "setup expression" argument.

Pseudocode:

foreach iteration
  eval(setup)
#start timing
  total += time(eval(expr))
#end timing
end
return total

Sometimes you want to generate new data for each timing iteration without including the setup in the timing.

**Comment by joshuaulrich** [comment]
I don't understand this use case.  Changing the data for each timing iteration adds additional variability to the results, which makes it difficult-to-impossible to draw inference from the results.

Could you please elaborate?  It would also help if you could provide a more specific example of why you want this behavior.

**Comment by thk686** [comment]
The specific example was testing an in-place sort on random data. Once the
data are sorted the first time, subsequent runs are much faster so I'd like
to regenerate the data before each evaluation. I suppose there are
work-arounds using iterators. I thought a general solution would be to have
a "setup" expression that runs before each trial.

**Comment by joshuaulrich** [comment]
Thank you, now I understand the use case.

**Comment by thk686** [comment]
I tried the following:

`> x = matrix_to_tuples(matrix(runif(1e6), ncol = 2))
> microbenchmark(kd_sort(x))
Unit: milliseconds
       expr      min       lq    mean   median       uq      max neval
 kd_sort(x) 108.1735 111.0402 111.797 111.4245 111.9707 120.5587   100
> microbenchmark(kd_sort(x), setup = {x = matrix_to_tuples(matrix(runif(1e6), ncol = 2))})
Unit: milliseconds
       expr      min      lq    mean   median       uq      max neval
 kd_sort(x) 107.6907 110.503 111.306 110.9118 111.7024 118.8845   100
> microbenchmark(kd_sort(x, inplace = TRUE))
Unit: milliseconds
                       expr     min       lq     mean  median       uq
 kd_sort(x, inplace = TRUE) 16.9268 17.10451 18.62687 17.4376 18.27395
      max neval
 106.4538   100
> microbenchmark(kd_sort(x, inplace = TRUE), setup = {x = matrix_to_tuples(matrix(runif(1e6), ncol = 2))})
Unit: milliseconds
                       expr      min      lq     mean   median       uq
 kd_sort(x, inplace = TRUE) 16.91099 17.1023 18.94723 17.49184 18.97184
      max neval
 104.3782   100
> `

I would expect the final trial to match the first. Instead, it looks like the original `x` was sorted repeatedly rather than a newly generated `x`. The `max` value is the first sort and the rest are re-sorts of the same data.

**Comment by joshuaulrich** [comment]
Thanks for testing! I just pushed a commit that works for your posted example, and I added a few more tests that pass. I appreciate any more feedback you have.

**Comment by thk686** [comment]
That works. Only issue I can think of is a better name for 'setup'. (I know I suggested it originally.) Perhaps 'for_each' or 'generate' or something indicating its run each time? Up to you.

**Comment by joshuaulrich** [comment]
I looked a some benchmark packages in other languages to assess whether they have this functionality and how it's named.

* [Java JMH](http://hg.openjdk.java.net/code-tools/jmh/file/tip/jmh-core/src/main/java/org/openjdk/jmh/annotations/Level.java) uses a `@Setup(Level)` annotation, with the following levels:
  1. Trial level: to be executed before/after each run of the benchmark.
  1. Iteration level: to be executed before/after each iteration of the benchmark.
  1. Invocation level: to be executed for each benchmark method execution.
* [Benchmark.js](https://benchmarkjs.com/) has a [`prototype_setup`](https://benchmarkjs.com/docs#prototype_setup) that is run before the test loop.  It also has callbacks, where [`onStart`](https://benchmarkjs.com/docs#options_onStart) looks the most similar to our `setup`.
* A [google benchmark](https://github.com/google/benchmark/) issue has [a comment](https://github.com/google/benchmark/issues/238#issuecomment-224741036) that says xUnit-based benchmark libraries have something like `SetupTestCase()`.
