### ISSUE TITLE
Validity of 'unit' argument should be tested earlier

### ISSUE THREAD

**Issue by xrobin** [joshuaulrich/microbenchmark#20]
### Description

Invalid `unit` arguments aren't detected immediately:

    f <- function() NULL
    res <- microbenchmark(NULL, f(), times=1000L, unit = "milisecond")

It is only upon print that an error is generated:

     > res
     Error in match.arg(unit) : 
      'arg' should be one of "ns", "us", "ms", "s", "t", "hz", "khz", "mhz", "eps", "f"

This means that I can waste a very long time running a benchmark that I'll never be able to use (at least not normally, I guess I could still extract the data manually if really needed but that's not optimal)

### Expected behavior

Invalid `unit` value should raise an error as soon as possible at the very beginning of the call to `microbenchmark` to avoid running a long benchmark only to realize the unit was set wrong.

    res <- microbenchmark(NULL, f(), times=1000L, unit = "milisecond")
    Error in match.arg(unit) : 
     'arg' should be one of "ns", "us", "ms", "s", "t", "hz", "khz", "mhz", "eps", "f"

### Minimal, reproducible example

```r
    f <- function() NULL
    res <- microbenchmark(NULL, f(), times=1000L, unit = "milisecond")
    print(res)
```

### Session Info

```r
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=C                 LC_NUMERIC=C              
 [3] LC_TIME=fr_CH.UTF-8        LC_COLLATE=C              
 [5] LC_MONETARY=fr_CH.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=fr_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbenchmark_1.4-6

loaded via a namespace (and not attached):
[1] tools_3.5.3
```

**Comment by elmstedt** [comment]
I know this is old, but in the hopes it can help someone with the same issue...
You don't need to lose your results (and time). You can _fix_ the unit after benchmarking like so,
``` r
x <- runif(1e3)
microbenchmark(
  mean(x),
  unit = "nanoseconds"
)
#> Error in microbenchmark(mean(x), unit = "nanoseconds"): could not find function "microbenchmark"
mbr <- .Last.value
attr(mbr, "unit") <- "ns"
mbr
# Unit: nanoseconds
#     expr  min   lq    mean median   uq   max neval
#  mean(x) 3800 3801 4217.01   3901 4001 26200   100
#> attr(,"unit")
#> [1] "ns"
```
<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Possible fixes would include,
1. In `microbenchmark()`, perform a check for a valid unit and issue a warning and default to `unit = t` there.
2. In `summary.microbenchmark()`, turn the error into a warning and defaulting to `unit = t` as is done when the `unit` argument is missing.

**Comment by joshuaulrich** [comment]
Thanks for bumping this suggestion. I will make sure it's added in the next release.

**Comment by joshuaulrich** [comment]
Sorry this took so long to fix!  It will be in the next release.

@xrobin note that I added support for more unit values, so `unit = "millisecond"` will work now.

**Comment by elmstedt** [comment]
While you're at it may I recommend you add, if for no other reason but completeness, units for minutes, hours, and maybe days?

I know no one is going to do 100 of more replications of anything which takes one or more days to complete, but it doesn't really cost anything to add.
