### ISSUE TITLE
Default `unit = "relative"` not accepted (anymore) in `microbenchmark`

### ISSUE THREAD

**Issue by tappek** [joshuaulrich/microbenchmark#34]
This used to work
`microbenchmark::microbenchmark(TRUE, FALSE, unit = "relative")`
but in version 1.4.9 (and maybe the previous version) it errors with:
```
Error in match.arg(unit, values) : 
  'arg' should be one of “nanoseconds”, “ns”, “microseconds”, “us”, “milliseconds”, “ms”, “seconds”, “s”, “secs”, “time”, “t”, “frequency”, “f”, “hz”, “khz”, “mhz”, “eps”
```

Could #20 and the associated commit 6533560926ff57ef845c4ad86fc17aa7d30d0997 be the culprit?

Passing `unit = "relative"` directly to summary still works. 
```
mb <- microbenchmark::microbenchmark(TRUE, FALSE)
summary(mb, unit = "relative")
```

**Comment by richierocks** [comment]
I just fell over this same issue. The workaround is straightforward, but having to explicitly all `print()` is not very idiomatic R code.

```r
# This causes an error in recent versions 
microbenchmark(TRUE, FALSE, unit="relative")
#> Error in match.arg(unit, values): 'arg' should be one of "nanoseconds", "ns", "microseconds", "us", "milliseconds", "ms", "seconds", "s", "secs", "time", "t", "frequency", "f", "hz", "khz", "mhz", "eps"

# This is the workaround
res <- microbenchmark(TRUE, FALSE)
print(res, unit="relative")
#> Unit: relative
#>   expr min lq     mean median uq      max neval
#>   TRUE 1.0  1 1.000000      1  1  1.00000   100
#>  FALSE 1.5  1 5.661927      1  1 48.81356   100
```

**Comment by joshuaulrich** [comment]
Thanks for the report @tappek! And thanks for the bump @richierocks. I just pushed a branch with a potential fix. Please test and report back. Thank you both again!

**Comment by joshuaulrich** [comment]
Hey @tappek and @richierocks, can you please let me know if this branch fixes the issue?
`remotes::install_github("joshuaulrich/microbenchmark@34-unit-relative")`

**Comment by tappek** [comment]
Works for me! Thank you!

**Comment by richierocks** [comment]
Sorry for delayed response. Yes, this works. Thanks for the fix.
