### ISSUE TITLE
`summary.microbenchmark()` does not pass parameters to `print.data.frame()`

### ISSUE THREAD

**Issue by tinygreen** [joshuaulrich/microbenchmark#47]
### Description

`summary.microbenchmark()` has a signature that includes `...`
https://github.com/joshuaulrich/microbenchmark/blob/676130d11f6f1c31cfd7c68d3a319a5c00ab6aba/R/summary.R#L26

According to the function documentation the `...` is passed to `print.data.frame()`
https://github.com/joshuaulrich/microbenchmark/blob/676130d11f6f1c31cfd7c68d3a319a5c00ab6aba/R/summary.R#L10

But there are no calls to `print.data.frame()` in `summary.microbenchmark()`. It just returns the calculated summary as a `data.frame`.
https://github.com/joshuaulrich/microbenchmark/blob/676130d11f6f1c31cfd7c68d3a319a5c00ab6aba/R/summary.R#L22

### Expected behavior

The function documentation should match what is actually happening. Either the function documentation should specify that `...` is ignored, or `...` should be removed from the signature entirely. The latter may break code that is already passing extra parameters, which are currently just ignored.

### Minimal, reproducible example

``` r
library(microbenchmark)
res <- microbenchmark(rchisq(1000, 1), rchisq(1000, 2), unit = "us")

# This will print the summary, ignoring the digits parameter
summary(res, digits = 2)
#>              expr   min     lq    mean median    uq   max neval cld
#> 1 rchisq(1000, 1) 110.6 115.35 121.772 117.10 121.7 179.8   100  a 
#> 2 rchisq(1000, 2)  67.5  72.95  78.561  76.15  80.2 125.0   100   b

# While if we store the result and actually pass the param to print.data.frame
smry <- summary(res)
print(smry, digits = 2)
#>              expr min  lq mean median  uq max neval cld
#> 1 rchisq(1000, 1) 111 115  122    117 122 180   100  a 
#> 2 rchisq(1000, 2)  68  73   79     76  80 125   100   b
```

**Comment by joshuaulrich** [comment]
Thanks for the report and PR!
